# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:

      - checkout: { path: ~/repo }
      
      - setup_remote_docker

      - run:
          name: Login to heroku docker
          command: docker login -u $HEROKU_EMAIL -p $HEROKU_PASS registry.heroku.com

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
 
      - run: yarn build:server

      - run:
          name: Deploy Master to Heroku
          command: |
            TAG=$CIRCLE_BRANCH-$CIRCLE_SHA1
            docker build -f Dockerfile.prod -t trabian/banking-api:$TAG .
            docker tag trabian/trabian-banking-api:$TAG registry.heroku.com/trabian-banking-api/web
            docker push registry.heroku.com/trabian-banking-api/web